import { tr } from "date-fns/locale";

// Main application data object for PLX Energy Transportation Expertise
export const AdminData = {
  // ===== Dashboard: Top Stat Cards (3 total on UI) =====
  dashboardStats: [
    {
      title: "Nomination Submitted",
      value: 21,
      change: "15%",
      RightIcon: "SubmitIcon",
    },
    {
      title: "Nomination Confirmed",
      value: 15,
      change: "6%",
      RightIcon: "ConfirmIcon",
    },
    {
      title: "Total Schedules",
      value: 37,
      change: "6%",
      RightIcon: "StarCalenderIcon",
    },
  ],

  // ===== Dashboard: Schedule Statistics (line/area chart) =====
  scheduleStatistics: [
    { month: "Jan", value: 980 },
    { month: "Feb", value: 1200 },
    { month: "Mar", value: 1100 },
    { month: "Apr", value: 1350 },
    { month: "May", value: 1500 },
    { month: "Jun", value: 1400 },
    { month: "Jul", value: 1600 },
    { month: "Aug", value: 1750 },
    { month: "Sep", value: 1650 },
    { month: "Oct", value: 1800 },
    { month: "Nov", value: 1700 },
    { month: "Dec", value: 1750 },
  ],

  // ===== Dashboard: User Statistics (donut) =====
  userStatistics: [
    { total: 2442, visitors: 820, users: 740, subscribers: 882 },
  ],

  // ===== Users/Subscribers Data =====
  users: [
    {
      id: 1,
      name: "Sarah Chen",
      nameCode: "SARAH_CHEN",
      email: "debbie.baker@example.com",
      company: "Energy Solutions Inc.",
      companyCode: "ENERGY_SOLUTIONS",
      role: "subscriber",
      roleCode: "SUBSCRIBER",
      avatar: "SC",
      status: "active",
      statusCode: "ACTIVE",
      isVerified: true,
      lastLogin: "2025-08-22T09:30:00Z",
      createdAt: "2025-01-15T00:00:00Z",
      updatedAt: "2025-08-22T09:30:00Z",
    },
    {
      id: 2,
      name: "Esther Howard",
      nameCode: "ESTHER_HOWARD",
      email: "michael.mitc@example.com",
      company: "Power Grid Corp",
      companyCode: "POWER_GRID",
      role: "subscriber",
      roleCode: "SUBSCRIBER",
      avatar: "EH",
      status: "active",
      statusCode: "ACTIVE",
      isVerified: true,
      lastLogin: "2025-08-22T08:45:00Z",
      createdAt: "2025-02-20T00:00:00Z",
      updatedAt: "2025-08-22T08:45:00Z",
    },
    {
      id: 3,
      name: "Brooklyn Simmons",
      nameCode: "BROOKLYN_SIMMONS",
      email: "deanna.curtis@example.com",
      company: "Gas Transport Ltd",
      companyCode: "GAS_TRANSPORT",
      role: "subscriber",
      roleCode: "SUBSCRIBER",
      avatar: "BS",
      status: "active",
      statusCode: "ACTIVE",
      isVerified: true,
      lastLogin: "2025-08-22T10:15:00Z",
      createdAt: "2025-03-10T00:00:00Z",
      updatedAt: "2025-08-22T10:15:00Z",
    },
    {
      id: 4,
      name: "Leslie Alexander",
      nameCode: "LESLIE_ALEXANDER",
      email: "michael.mitc@example.com",
      company: "Energy Flow Inc",
      companyCode: "ENERGY_FLOW",
      role: "subscriber",
      roleCode: "SUBSCRIBER",
      avatar: "LA",
      status: "active",
      statusCode: "ACTIVE",
      isVerified: true,
      lastLogin: "2025-08-22T07:20:00Z",
      createdAt: "2025-04-05T00:00:00Z",
      updatedAt: "2025-08-22T07:20:00Z",
    },
    {
      id: 5,
      name: "Jenny Wilson",
      nameCode: "JENNY_WILSON",
      email: "tim.jennings@example.com",
      company: "Binford Ltd",
      companyCode: "BINFORD_LTD",
      role: "admin",
      roleCode: "ADMIN",
      avatar: "JW",
      status: "active",
      statusCode: "ACTIVE",
      isVerified: true,
      lastLogin: "2025-08-22T11:00:00Z",
      createdAt: "2025-01-01T00:00:00Z",
      updatedAt: "2025-08-22T11:00:00Z",
    },
    {
      id: 6,
      name: "Miguel Trevino",
      nameCode: "MIGUEL_TREVINO",
      email: "miguel.trevino@plx.com",
      company: "PLX Energy",
      companyCode: "PLX_ENERGY",
      role: "admin",
      roleCode: "ADMIN",
      avatar: "MT",
      status: "active",
      statusCode: "ACTIVE",
      isVerified: true,
      lastLogin: "2025-08-22T12:30:00Z",
      createdAt: "2025-01-01T00:00:00Z",
      updatedAt: "2025-08-22T12:30:00Z",
    },
  ],

  // ===== Commodity Types =====
  commodities: [
    {
      id: 1,
      name: "Natural Gas",
      nameCode: "NATURAL_GAS",
      category: "gas",
      categoryCode: "GAS",
      unit: "MMBtu",
      unitCode: "MMBTU",
      description: "Natural gas for energy distribution",
      status: "active",
      statusCode: "ACTIVE",
      isAvailable: true,
      pricePerUnit: 3.5,
      currency: "USD",
      createdAt: "2025-01-01T00:00:00Z",
      updatedAt: "2025-08-22T00:00:00Z",
    },
    {
      id: 2,
      name: "Crude Oil - WTI",
      nameCode: "CRUDE_OIL_WTI",
      category: "oil",
      categoryCode: "OIL",
      unit: "bbls",
      unitCode: "BBLS",
      description: "West Texas Intermediate crude oil",
      status: "active",
      statusCode: "ACTIVE",
      isAvailable: true,
      pricePerUnit: 75.25,
      currency: "USD",
      createdAt: "2025-01-01T00:00:00Z",
      updatedAt: "2025-08-22T00:00:00Z",
    },
    {
      id: 3,
      name: "Electricity",
      nameCode: "ELECTRICITY",
      category: "power",
      categoryCode: "POWER",
      unit: "MWh",
      unitCode: "MWH",
      description: "Electrical energy for grid distribution",
      status: "active",
      statusCode: "ACTIVE",
      isAvailable: true,
      pricePerUnit: 45.8,
      currency: "USD",
      createdAt: "2025-01-01T00:00:00Z",
      updatedAt: "2025-08-22T00:00:00Z",
    },
    {
      id: 4,
      name: "LNG",
      nameCode: "LNG",
      category: "gas",
      categoryCode: "GAS",
      unit: "MMBtu",
      unitCode: "MMBTU",
      description: "Liquefied Natural Gas",
      status: "active",
      statusCode: "ACTIVE",
      isAvailable: true,
      pricePerUnit: 4.2,
      currency: "USD",
      createdAt: "2025-01-01T00:00:00Z",
      updatedAt: "2025-08-22T00:00:00Z",
    },
    {
      id: 5,
      name: "Petrochemicals",
      nameCode: "PETROCHEMICALS",
      category: "chemical",
      categoryCode: "CHEMICAL",
      unit: "tons",
      unitCode: "TONS",
      description: "Chemical products derived from petroleum",
      status: "active",
      statusCode: "ACTIVE",
      isAvailable: true,
      pricePerUnit: 1250.0,
      currency: "USD",
      createdAt: "2025-01-01T00:00:00Z",
      updatedAt: "2025-08-22T00:00:00Z",
    },
  ],

  // ===== Transport Modes =====
  transportModes: [
    {
      id: 1,
      name: "Pipeline",
      nameCode: "PIPELINE",
      color: "blue",
      colorCode: "BLUE",
      description: "Underground pipeline transportation",
      capacity: "high",
      capacityCode: "HIGH",
      cost: "low",
      costCode: "LOW",
      status: "active",
      statusCode: "ACTIVE",
      isAvailable: true,
      createdAt: "2025-01-01T00:00:00Z",
      updatedAt: "2025-08-22T00:00:00Z",
    },
    {
      id: 2,
      name: "Trucking",
      nameCode: "TRUCKING",
      color: "green",
      colorCode: "GREEN",
      description: "Road transport via trucks",
      capacity: "medium",
      capacityCode: "MEDIUM",
      cost: "medium",
      costCode: "MEDIUM",
      status: "active",
      statusCode: "ACTIVE",
      isAvailable: true,
      createdAt: "2025-01-01T00:00:00Z",
      updatedAt: "2025-08-22T00:00:00Z",
    },
    {
      id: 3,
      name: "Railcar",
      nameCode: "RAILCAR",
      color: "purple",
      colorCode: "PURPLE",
      description: "Rail transportation",
      capacity: "high",
      capacityCode: "HIGH",
      cost: "medium",
      costCode: "MEDIUM",
      status: "active",
      statusCode: "ACTIVE",
      isAvailable: true,
      createdAt: "2025-01-01T00:00:00Z",
      updatedAt: "2025-08-22T00:00:00Z",
    },
    {
      id: 4,
      name: "Marine",
      nameCode: "MARINE",
      color: "yellow",
      colorCode: "YELLOW",
      description: "Water transport via ships",
      capacity: "very_high",
      capacityCode: "VERY_HIGH",
      cost: "low",
      costCode: "LOW",
      status: "active",
      statusCode: "ACTIVE",
      isAvailable: true,
      createdAt: "2025-01-01T00:00:00Z",
      updatedAt: "2025-08-22T00:00:00Z",
    },
  ],

  // ===== Locations =====
  locations: [
    {
      id: 1,
      city: "Houston",
      cityCode: "HOUSTON",
      state: "TX",
      stateCode: "TEXAS",
      country: "USA",
      countryCode: "USA",
      type: "origin",
      typeCode: "ORIGIN",
      facilities: ["Port of Houston", "Energy Corridor"],
      status: "active",
      statusCode: "ACTIVE",
      isAvailable: true,
      coordinates: {
        latitude: 29.7604,
        longitude: -95.3698,
      },
      createdAt: "2025-01-01T00:00:00Z",
      updatedAt: "2025-08-22T00:00:00Z",
    },
    {
      id: 2,
      city: "Dallas",
      cityCode: "DALLAS",
      state: "TX",
      stateCode: "TEXAS",
      country: "USA",
      countryCode: "USA",
      type: "destination",
      typeCode: "DESTINATION",
      facilities: ["Dallas Energy Hub", "Transportation Center"],
      status: "active",
      statusCode: "ACTIVE",
      isAvailable: true,
      coordinates: {
        latitude: 32.7767,
        longitude: -96.797,
      },
      createdAt: "2025-01-01T00:00:00Z",
      updatedAt: "2025-08-22T00:00:00Z",
    },
    {
      id: 3,
      city: "Austin",
      cityCode: "AUSTIN",
      state: "TX",
      stateCode: "TEXAS",
      country: "USA",
      countryCode: "USA",
      type: "origin",
      typeCode: "ORIGIN",
      facilities: ["Austin Energy", "Central Hub"],
      status: "active",
      statusCode: "ACTIVE",
      isAvailable: true,
      coordinates: {
        latitude: 30.2672,
        longitude: -97.7431,
      },
      createdAt: "2025-01-01T00:00:00Z",
      updatedAt: "2025-08-22T00:00:00Z",
    },
    {
      id: 4,
      city: "San Antonio",
      cityCode: "SAN_ANTONIO",
      state: "TX",
      stateCode: "TEXAS",
      country: "USA",
      countryCode: "USA",
      type: "destination",
      typeCode: "DESTINATION",
      facilities: ["San Antonio Energy", "South Hub"],
      status: "active",
      statusCode: "ACTIVE",
      isAvailable: true,
      coordinates: {
        latitude: 29.4241,
        longitude: -98.4936,
      },
      createdAt: "2025-01-01T00:00:00Z",
      updatedAt: "2025-08-22T00:00:00Z",
    },
    {
      id: 5,
      city: "Cushing",
      cityCode: "CUSHING",
      state: "OK",
      stateCode: "OKLAHOMA",
      country: "USA",
      countryCode: "USA",
      type: "destination",
      typeCode: "DESTINATION",
      facilities: ["Cushing Hub", "Oil Storage"],
      status: "active",
      statusCode: "ACTIVE",
      isAvailable: true,
      coordinates: {
        latitude: 35.9851,
        longitude: -96.767,
      },
      createdAt: "2025-01-01T00:00:00Z",
      updatedAt: "2025-08-22T00:00:00Z",
    },
  ],

  // ===== Dashboard: Nominations table =====
  nominations: [
    {
      id: "3583475",
      subscriber: "Sarah Chen",
      company: "Energy Solutions Inc.",
      subscriberId: 1,
      email: "debbie.baker@example.com",
      requestedDate: "2025-08-25",
      commodity: "Natural Gas",
      commodityId: 1,
      volume: "50,000",
      unit: "MMBtu",
      origin: "Houston, TX",
      originId: 1,
      destination: "Dallas, TX",
      destinationId: 2,
      transport: "Pipeline",
      transportId: 1,
      beginDate: "2025-08-25",
      endDate: "2025-08-25",
      status: "submitted",
      statusCode: "SUBMITTED",
      statusColor: "blue",
      priority: "high",
      priorityCode: "HIGH",
      priorityColor: "red",
      notes: "Urgent delivery required",
      createdAt: "2025-08-25T10:00:00Z",
      updatedAt: "2025-08-25T10:00:00Z",
      isActive: true,
    },
    {
      id: "3583476",
      subscriber: "Esther Howard",
      company:'Caterpillar Inc.',
      subscriberId: 2,
      email: "michael.mitc@example.com",
      requestedDate: "2025-08-25",
      commodity: "Electricity",
      commodityId: 3,
      volume: "100",
      unit: "MWh",
      origin: "Austin, TX",
      originId: 3,
      destination: "San Antonio, TX",
      destinationId: 4,
      transport: "Trucking",
      transportId: 2,
      beginDate: "2025-08-25",
      endDate: "2025-08-25",
      status: "confirmed",
      statusCode: "CONFIRMED",
      statusColor: "green",
      priority: "medium",
      priorityCode: "MEDIUM",
      priorityColor: "yellow",
      notes: "Standard delivery",
      createdAt: "2025-08-25T10:00:00Z",
      updatedAt: "2025-08-25T10:00:00Z",
      isActive: true,
    },
    {
      id: "3583477",
      subscriber: "Brooklyn Simmons",
      company:' Chevron Corporation',
      subscriberId: 3,
      email: "deanna.curtis@example.com",
      requestedDate: "2025-08-25",
      commodity: "Natural Gas",
      commodityId: 1,
      volume: "75,000",
      unit: "MMBtu",
      origin: "San Antonio, TX",
      originId: 4,
      destination: "Dallas, TX",
      destinationId: 2,
      transport: "Trucking",
      transportId: 2,
      beginDate: "2025-08-25",
      endDate: "2025-08-25",
      status: "confirmed",
      statusCode: "CONFIRMED",
      statusColor: "green",
      priority: "low",
      priorityCode: "LOW",
      priorityColor: "gray",
      notes: "Flexible timing",
      createdAt: "2025-08-25T10:00:00Z",
      updatedAt: "2025-08-25T10:00:00Z",
      isActive: true,
    },
    {
      id: "3583478",
      subscriber: "Leslie Alexander",
      company:' ConocoPhillips',
      subscriberId: 4,
      email: "michael.mitc@example.com",
      requestedDate: "2025-08-25",
      commodity: "Electricity",
      commodityId: 3,
      volume: "150",
      unit: "MWh",
      origin: "Houston, TX",
      originId: 1,
      destination: "Dallas, TX",
      destinationId: 2,
      transport: "Railcar",
      transportId: 3,
      beginDate: "2025-08-25",
      endDate: "2025-08-25",
      status: "submitted",
      statusCode: "SUBMITTED",
      statusColor: "blue",
      priority: "medium",
      priorityCode: "MEDIUM",
      priorityColor: "yellow",
      notes: "Bulk delivery",
      createdAt: "2025-08-25T10:00:00Z",
      updatedAt: "2025-08-25T10:00:00Z",
      isActive: true,
    },
    {
      id: "3583479",
      subscriber: "Jenny Wilson",
      company:' Shell Oil Company',
      subscriberId: 5,
      email: "tim.jennings@example.com",
      requestedDate: "2025-08-25",
      commodity: "Natural Gas",
      commodityId: 1,
      volume: "25,000",
      unit: "MMBtu",
      origin: "Houston, TX",
      originId: 1,
      destination: "Dallas, TX",
      destinationId: 2,
      transport: "Railcar",
      transportId: 3,
      beginDate: "2025-08-25",
      endDate: "2025-08-25",
      status: "submitted",
      statusCode: "SUBMITTED",
      statusColor: "blue",
      priority: "low",
      priorityCode: "LOW",
      priorityColor: "gray",
      notes: "Regular schedule",
      createdAt: "2025-08-25T10:00:00Z",
      updatedAt: "2025-08-25T10:00:00Z",
      isActive: true,
    },
    {
      id: "3583480",
      subscriber: "Jenny Wilson",
      company:'FedEx Corporation',
      subscriberId: 5,
      email: "tim.jennings@example.com",
      requestedDate: "2025-08-25",
      commodity: "Natural Gas",
      commodityId: 1,
      volume: "30,000",
      unit: "MMBtu",
      origin: "Houston, TX",
      originId: 1,
      destination: "Dallas, TX",
      destinationId: 2,
      transport: "Marine",
      transportId: 4,
      beginDate: "2025-08-25",
      endDate: "2025-08-25",
      status: "confirmed",
      statusCode: "CONFIRMED",
      statusColor: "green",
      priority: "medium",
      priorityCode: "MEDIUM",
      priorityColor: "yellow",
      notes: "Water route preferred",
      createdAt: "2025-08-25T10:00:00Z",
      updatedAt: "2025-08-25T10:00:00Z",
      isActive: true,
    },
    {
      id: "3583481",
      subscriber: "Jenny Wilson",
      company:'Binford Ltd',
      subscriberId: 5,
      email: "tim.jennings@example.com",
      requestedDate: "2025-08-25",
      commodity: "Natural Gas",
      commodityId: 1,
      volume: "40,000",
      unit: "MMBtu",
      origin: "Houston, TX",
      originId: 1,
      destination: "Dallas, TX",
      destinationId: 2,
      transport: "Pipeline",
      transportId: 1,
      beginDate: "2025-08-25",
      endDate: "2025-08-25",
      status: "submitted",
      statusCode: "SUBMITTED",
      statusColor: "blue",
      priority: "high",
      priorityCode: "HIGH",
      priorityColor: "red",
      notes: "Pipeline capacity check needed",
      createdAt: "2025-08-25T10:00:00Z",
      updatedAt: "2025-08-25T10:00:00Z",
      isActive: true,
    },
  ],

  // ===== Dashboard: Upcoming Meetings table =====
  meetings: [
    {
      id: 1,
      user: "Sarah Chen",
      companyName:"Caterpillar Inc.",
      userId: 1,
      email: "debbie.baker@example.com",
      requestDate: "2025-08-21",
      meetingDate: "2025-08-21",
      time: "3:00PM",
      timeZone: "Pacific Time - US",
      timeZoneId: 1,
      duration: "02:30 Hrs",
      durationMinutes: 150,
      subject: "Quotation Review Discussion",
      status: "scheduled",
      statusCode: "SCHEDULED",
      statusColor: "blue",
      type: "quotation_review",
      typeCode: "QUOTATION_REVIEW",
      priority: "medium",
      priorityCode: "MEDIUM",
      priorityColor: "yellow",
      meetingType: "video_call",
      meetingTypeCode: "VIDEO_CALL",
      participants: ["Sarah Chen", "Miguel Trevino"],
      participantIds: [1, 6],
      notes: "Review quotation details and pricing",
      isRecurring: false,
      isActive: true,
      createdAt: "2025-08-20T10:00:00Z",
      updatedAt: "2025-08-21T15:00:00Z",
    },
    {
      id: 2,
      user: "Esther Howard",
      companyName:'Chevron Corporation',
      userId: 2,
      email: "michael.mitc@example.com",
      requestDate: "2025-08-23",
      meetingDate: "2025-08-23",
      time: "2:40PM",
      timeZone: "Central Time - US",
      timeZoneId: 2,
      duration: "02:30 Hrs",
      durationMinutes: 150,
      subject: "Compliance Call Request",
      status: "scheduled",
      statusCode: "SCHEDULED",
      statusColor: "blue",
      type: "compliance",
      typeCode: "COMPLIANCE",
      priority: "high",
      priorityCode: "HIGH",
      priorityColor: "red",
      meetingType: "phone_call",
      meetingTypeCode: "PHONE_CALL",
      participants: ["Esther Howard", "Miguel Trevino"],
      participantIds: [2, 6],
      notes: "Discuss compliance requirements and regulations",
      isRecurring: false,
      isActive: true,
      createdAt: "2025-08-22T14:00:00Z",
      updatedAt: "2025-08-23T14:40:00Z",
    },
    {
      id: 3,
      user: "Brooklyn Simmons",
      companyName:'ConocoPhillips',
      userId: 3,
      email: "deanna.curtis@example.com",
      requestDate: "2025-08-24",
      meetingDate: "2025-08-24",
      time: "10:00AM",
      timeZone: "Mountain Time - US",
      timeZoneId: 4,
      duration: "02:30 Hrs",
      durationMinutes: 150,
      subject: "Pricing Negotiation on services",
      status: "scheduled",
      statusCode: "SCHEDULED",
      statusColor: "blue",
      type: "pricing",
      typeCode: "PRICING",
      priority: "medium",
      priorityCode: "MEDIUM",
      priorityColor: "yellow",
      meetingType: "video_call",
      meetingTypeCode: "VIDEO_CALL",
      participants: ["Brooklyn Simmons", "Miguel Trevino"],
      participantIds: [3, 6],
      notes: "Negotiate service pricing and terms",
      isRecurring: false,
      isActive: true,
      createdAt: "2025-08-23T09:00:00Z",
      updatedAt: "2025-08-24T10:00:00Z",
    },
    {
      id: 4,
      user: "Leslie Alexander",
      companyName:' Shell Oil Company',
      userId: 4,
      email: "michael.mitc@example.com",
      requestDate: "2025-08-25",
      meetingDate: "2025-08-25",
      time: "9:00AM",
      timeZone: "Eastern Time - US",
      timeZoneId: 3,
      duration: "02:30 Hrs",
      durationMinutes: 150,
      subject: "Contract Review of services",
      status: "scheduled",
      statusCode: "SCHEDULED",
      statusColor: "blue",
      type: "contract",
      typeCode: "CONTRACT",
      priority: "high",
      priorityCode: "HIGH",
      priorityColor: "red",
      meetingType: "in_person",
      meetingTypeCode: "IN_PERSON",
      participants: ["Leslie Alexander", "Miguel Trevino"],
      participantIds: [4, 6],
      notes: "Review and finalize service contract",
      isRecurring: false,
      isActive: true,
      createdAt: "2025-08-24T11:00:00Z",
      updatedAt: "2025-08-25T09:00:00Z",
    },
    {
      id: 5,
      user: "Jenny Wilson",
      companyName:'Binford Ltd',
      userId: 5,
      email: "tim.jennings@example.com",
      requestDate: "2025-08-26",
      meetingDate: "2025-08-26",
      time: "11:00AM",
      timeZone: "Alaska Time",
      timeZoneId: 5,
      duration: "02:30 Hrs",
      durationMinutes: 150,
      subject: "Logistics Planning Discussion",
      status: "scheduled",
      statusCode: "SCHEDULED",
      statusColor: "blue",
      type: "logistics",
      typeCode: "LOGISTICS",
      priority: "medium",
      priorityCode: "MEDIUM",
      priorityColor: "yellow",
      meetingType: "video_call",
      meetingTypeCode: "VIDEO_CALL",
      participants: ["Jenny Wilson", "Miguel Trevino"],
      participantIds: [5, 6],
      notes: "Plan logistics and transportation routes",
      isRecurring: false,
      isActive: true,
      createdAt: "2025-08-25T13:00:00Z",
      updatedAt: "2025-08-26T11:00:00Z",
    },
    {
      id: 6,
      user: "Jane Cooper",
      companyName:'FedEx Corporation',
      userId: 7,
      email: "jane.cooper@example.com",
      requestDate: "2025-08-01",
      meetingDate: "2025-08-01",
      time: "4:20PM",
      timeZone: "Central Time - US",
      timeZoneId: 2,
      duration: "01:00 Hrs",
      durationMinutes: 60,
      subject: "Initial Consultation",
      status: "scheduled",
      statusCode: "SCHEDULED",
      statusColor: "blue",
      type: "consultation",
      typeCode: "CONSULTATION",
      priority: "low",
      priorityCode: "LOW",
      priorityColor: "gray",
      meetingType: "video_call",
      meetingTypeCode: "VIDEO_CALL",
      participants: ["Jane Cooper", "Miguel Trevino"],
      participantIds: [7, 6],
      notes: "Initial meeting to discuss services",
      isRecurring: false,
      isActive: true,
      createdAt: "2025-07-30T16:00:00Z",
      updatedAt: "2025-08-01T16:20:00Z",
    },
    {
      id: 7,
      user: "Wade Warren",
      userId: 8,
      email: "wade.warren@example.com",
      requestDate: "2025-08-07",
      meetingDate: "2025-08-07",
      time: "4:20PM",
      timeZone: "Central Time - US",
      timeZoneId: 2,
      duration: "01:30 Hrs",
      durationMinutes: 90,
      subject: "Project Kickoff",
      status: "scheduled",
      statusCode: "SCHEDULED",
      statusColor: "blue",
      type: "project",
      typeCode: "PROJECT",
      priority: "high",
      priorityCode: "HIGH",
      priorityColor: "red",
      meetingType: "video_call",
      meetingTypeCode: "VIDEO_CALL",
      participants: ["Wade Warren", "Miguel Trevino"],
      participantIds: [8, 6],
      notes: "Kickoff meeting for new transportation project",
      isRecurring: false,
      isActive: true,
      createdAt: "2025-08-05T14:00:00Z",
      updatedAt: "2025-08-07T16:20:00Z",
    },
    {
      id: 8,
      user: "Robert Fox",
      companyName:'PLX Energy',
      userId: 9,
      email: "robert.fox@example.com",
      requestDate: "2025-08-07",
      meetingDate: "2025-08-07",
      time: "4:20PM",
      timeZone: "Central Time - US",
      timeZoneId: 2,
      duration: "01:30 Hrs",
      durationMinutes: 90,
      subject: "Project Kickoff",
      status: "scheduled",
      statusCode: "SCHEDULED",
      statusColor: "blue",
      type: "project",
      typeCode: "PROJECT",
      priority: "high",
      priorityCode: "HIGH",
      priorityColor: "red",
      meetingType: "video_call",
      meetingTypeCode: "VIDEO_CALL",
      participants: ["Robert Fox", "Miguel Trevino"],
      participantIds: [9, 6],
      notes: "Kickoff meeting for new transportation project",
      isRecurring: false,
      isActive: true,
      createdAt: "2025-08-05T14:00:00Z",
      updatedAt: "2025-08-07T16:20:00Z",
    },
  ],

  // ===== Calendar View Data =====
  calendarMeetings: [
    {
      id: 1,
      date: "2025-08-01",
      dateCode: "2025-08-01",
      day: "Thursday",
      dayCode: "THURSDAY",
      meetings: [
        {
          id: 6,
          user: "Jane Cooper",
          userId: 7,
          time: "4:20PM",
          type: "consultation",
          typeCode: "CONSULTATION",
          color: "light-green",
          colorCode: "LIGHT_GREEN",
          status: "scheduled",
          statusCode: "SCHEDULED",
        },
        {
          id: 2,
          user: "Esther Howard",
          userId: 2,
          time: "4:20PM",
          type: "compliance",
          typeCode: "COMPLIANCE",
          color: "light-green",
          colorCode: "LIGHT_GREEN",
          status: "scheduled",
          statusCode: "SCHEDULED",
        },
      ],
      totalMeetings: 2,
      isActive: true,
      createdAt: "2025-07-30T00:00:00Z",
      updatedAt: "2025-08-01T00:00:00Z",
    },
    {
      id: 2,
      date: "2025-08-05",
      dateCode: "2025-08-05",
      day: "Monday",
      dayCode: "MONDAY",
      meetings: [
        {
          id: 6,
          user: "Jane Cooper",
          userId: 7,
          time: "4:20PM",
          type: "consultation",
          typeCode: "CONSULTATION",
          color: "blue",
          colorCode: "BLUE",
          status: "scheduled",
          statusCode: "SCHEDULED",
        },
        {
          id: 2,
          user: "Esther Howard",
          userId: 2,
          time: "4:20PM",
          type: "compliance",
          typeCode: "COMPLIANCE",
          color: "blue",
          colorCode: "BLUE",
          status: "scheduled",
          statusCode: "SCHEDULED",
        },
        {
          id: 10,
          user: "Additional User 1",
          userId: 18,
          time: "2:00PM",
          type: "general",
          typeCode: "GENERAL",
          color: "blue",
          colorCode: "BLUE",
          status: "scheduled",
          statusCode: "SCHEDULED",
        },
        {
          id: 11,
          user: "Additional User 2",
          userId: 19,
          time: "3:00PM",
          type: "general",
          typeCode: "GENERAL",
          color: "blue",
          colorCode: "BLUE",
          status: "scheduled",
          statusCode: "SCHEDULED",
        },
        {
          id: 12,
          user: "Additional User 3",
          userId: 20,
          time: "5:00PM",
          type: "general",
          typeCode: "GENERAL",
          color: "blue",
          colorCode: "BLUE",
          status: "scheduled",
          statusCode: "SCHEDULED",
        },
      ],
      totalMeetings: 5,
      isActive: true,
      createdAt: "2025-07-30T00:00:00Z",
      updatedAt: "2025-08-05T00:00:00Z",
    },
    {
      id: 3,
      date: "2025-08-07",
      dateCode: "2025-08-07",
      day: "Wednesday",
      dayCode: "WEDNESDAY",
      meetings: [
        {
          id: 7,
          user: "Wade Warren",
          userId: 8,
          time: "4:20PM",
          type: "project",
          typeCode: "PROJECT",
          color: "light-purple",
          colorCode: "LIGHT_PURPLE",
          status: "scheduled",
          statusCode: "SCHEDULED",
        },
        {
          id: 8,
          user: "Robert Fox",
          userId: 9,
          time: "4:20PM",
          type: "project",
          typeCode: "PROJECT",
          color: "light-purple",
          colorCode: "LIGHT_PURPLE",
          status: "scheduled",
          statusCode: "SCHEDULED",
        },
      ],
      totalMeetings: 2,
      isActive: true,
      createdAt: "2025-07-30T00:00:00Z",
      updatedAt: "2025-08-07T00:00:00Z",
    },
    {
      id: 4,
      date: "2025-08-08",
      dateCode: "2025-08-08",
      day: "Thursday",
      dayCode: "THURSDAY",
      meetings: [
        {
          id: 7,
          user: "Wade Warren",
          userId: 8,
          time: "4:20PM",
          type: "project",
          typeCode: "PROJECT",
          color: "light-purple",
          colorCode: "LIGHT_PURPLE",
          status: "scheduled",
          statusCode: "SCHEDULED",
        },
      ],
      totalMeetings: 1,
      isActive: true,
      createdAt: "2025-07-30T00:00:00Z",
      updatedAt: "2025-08-08T00:00:00Z",
    },
    {
      id: 5,
      date: "2025-08-10",
      dateCode: "2025-08-10",
      day: "Saturday",
      dayCode: "SATURDAY",
      meetings: [
        {
          id: 7,
          user: "Wade Warren",
          userId: 8,
          time: "4:20PM",
          type: "project",
          typeCode: "PROJECT",
          color: "light-purple",
          colorCode: "LIGHT_PURPLE",
          status: "scheduled",
          statusCode: "SCHEDULED",
        },
        {
          id: 8,
          user: "Robert Fox",
          userId: 9,
          time: "4:20PM",
          type: "project",
          typeCode: "PROJECT",
          color: "light-purple",
          colorCode: "LIGHT_PURPLE",
          status: "scheduled",
          statusCode: "SCHEDULED",
        },
        {
          id: 13,
          user: "Additional User 4",
          userId: 21,
          time: "1:00PM",
          type: "general",
          typeCode: "GENERAL",
          color: "light-purple",
          colorCode: "LIGHT_PURPLE",
          status: "scheduled",
          statusCode: "SCHEDULED",
        },
      ],
      totalMeetings: 3,
      isActive: true,
      createdAt: "2025-07-30T00:00:00Z",
      updatedAt: "2025-08-10T00:00:00Z",
    },
    {
      id: 6,
      date: "2025-08-15",
      dateCode: "2025-08-15",
      day: "Thursday",
      dayCode: "THURSDAY",
      meetings: [
        {
          id: 7,
          user: "Wade Warren",
          userId: 8,
          time: "4:20PM",
          type: "project",
          typeCode: "PROJECT",
          color: "light-purple",
          colorCode: "LIGHT_PURPLE",
          status: "scheduled",
          statusCode: "SCHEDULED",
        },
        {
          id: 8,
          user: "Robert Fox",
          userId: 9,
          time: "4:20PM",
          type: "project",
          typeCode: "PROJECT",
          color: "light-purple",
          colorCode: "LIGHT_PURPLE",
          status: "scheduled",
          statusCode: "SCHEDULED",
        },
        {
          id: 14,
          user: "Additional User 5",
          userId: 22,
          time: "3:00PM",
          type: "general",
          typeCode: "GENERAL",
          color: "light-purple",
          colorCode: "LIGHT_PURPLE",
          status: "scheduled",
          statusCode: "SCHEDULED",
        },
      ],
      totalMeetings: 3,
      isActive: true,
      createdAt: "2025-07-30T00:00:00Z",
      updatedAt: "2025-08-15T00:00:00Z",
    },
  ],

  // ===== Messages/Chat Data =====
  // messages: [
  //   {
  //     id: 1,
  //     contact: "Patrick Johnson",
  //     contactId: 10,
  //     avatar: "PJ",
  //     lastMessage:
  //       "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam pharetra felis et tortor scelerisque, id placerat augue hendrerit",
  //     timestamp: "Yesterday",
  //     unreadCount: 10,
  //     status: "online",
  //     lastSeen: "1 min ago",
  //   },
  //   {
  //     id: 2,
  //     contact: "Lisa Williams",
  //     contactId: 11,
  //     avatar: "LW",
  //     lastMessage: "Lorem ipsum dolor sit amet",
  //     timestamp: "20/08/2025",
  //     unreadCount: 0,
  //     status: "offline",
  //     lastSeen: "2 hours ago",
  //   },
  //   {
  //     id: 3,
  //     contact: "Josh Adams",
  //     contactId: 12,
  //     avatar: "JA",
  //     lastMessage: "Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
  //     timestamp: "20/08/2025",
  //     unreadCount: 4,
  //     status: "online",
  //     lastSeen: "30 min ago",
  //   },
  //   {
  //     id: 4,
  //     contact: "Jacob Trevor",
  //     contactId: 13,
  //     avatar: "JT",
  //     lastMessage: "Lorem ipsum dolor sit amet",
  //     timestamp: "20/08/2025",
  //     unreadCount: 3,
  //     status: "away",
  //     lastSeen: "1 hour ago",
  //   },
  //   {
  //     id: 5,
  //     contact: "Danny Johnson",
  //     contactId: 14,
  //     avatar: "DJ",
  //     lastMessage: "Lorem ipsum dolor sit amet",
  //     timestamp: "20/08/2025",
  //     unreadCount: 0,
  //     status: "offline",
  //     lastSeen: "3 hours ago",
  //   },
  //   {
  //     id: 6,
  //     contact: "Patricia Heather",
  //     contactId: 15,
  //     avatar: "PH",
  //     lastMessage: "Lorem ipsum dolor sit amet",
  //     timestamp: "20/08/2025",
  //     unreadCount: 0,
  //     status: "offline",
  //     lastSeen: "5 hours ago",
  //   },
  //   {
  //     id: 7,
  //     contact: "Michael Thomas",
  //     contactId: 16,
  //     avatar: "MT",
  //     lastMessage: "Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
  //     timestamp: "20/08/2025",
  //     unreadCount: 0,
  //     status: "offline",
  //     lastSeen: "1 day ago",
  //   },
  //   {
  //     id: 8,
  //     contact: "Linda Robert",
  //     contactId: 17,
  //     avatar: "LR",
  //     lastMessage: "Lorem ipsum dolor sit amet",
  //     timestamp: "20/08/2025",
  //     unreadCount: 0,
  //     status: "offline",
  //     lastSeen: "2 days ago",
  //   },
  // ],

 // isActive removed, isRead added
messages: [
    {
      user_id: 1001,
      customer_name: "Sarah Johnson",
      customer_image: "https://randomuser.me/api/portraits/women/44.jpg",
      isRead: false,
      last_seen: "2025-07-16T09:35:16",
      last_message: "It's #ORD-45678. The delivery date seems to have changed",
    },
    {
      user_id: 1002,
      customer_name: "Michael Carter",
      customer_image: "https://randomuser.me/api/portraits/men/65.jpg",
      isRead: true,
      last_seen: "2025-07-22T09:35:16",
      last_message: "I can help with that. Could you share the item details?",
    },
    {
      user_id: 1003,
      customer_name: "Emily Davis",
      customer_image: "https://randomuser.me/api/portraits/women/56.jpg",
      isRead: false,
      last_seen: "2025-07-31T09:35:16",
      last_message: "Thanks, I'd like to order it if available",
    },
    {
      user_id: 1004,
      customer_name: "Daniel Lee",
      customer_image: "https://randomuser.me/api/portraits/men/12.jpg",
      isRead: true,
      last_seen: "2025-07-29T09:35:16",
      last_message: "Appreciate it, order #ORD-98765",
    },
    {
      user_id: 1005,
      customer_name: "Sophia Martinez",
      customer_image: "https://randomuser.me/api/portraits/women/30.jpg",
      isRead: false,
      last_seen: "2025-08-08T10:30:11.578",
      last_message: "It's #ORD-12345, thanks for checking",
    },
    {
      user_id: 1006,
      customer_name: "Liam Wilson",
      customer_image: "https://randomuser.me/api/portraits/men/23.jpg",
      isRead: false,
      last_seen: "2025-07-28T09:35:16",
      last_message: "It's your Model X200, priced at $299 elsewhere",
    },
    {
      user_id: 1007,
      customer_name: "Olivia Brown",
      customer_image: "https://randomuser.me/api/portraits/women/77.jpg",
      isRead: false,
      last_seen: "2025-07-14T09:35:16",
      last_message: "Thank you, I've attached photos of the damage",
    },
    {
      user_id: 1008,
      customer_name: "Noah Anderson",
      customer_image: "https://randomuser.me/api/portraits/men/35.jpg",
      isRead: false,
      last_seen: "2025-07-30T09:35:16",
      last_message: "Great, can you notify me when available?",
    },
    {
      user_id: 1009,
      customer_name: "Ava Thomas",
      customer_image: "https://randomuser.me/api/portraits/women/88.jpg",
      isRead: false,
      last_seen: "2025-07-15T09:35:16",
      last_message: "It's #TRK-789456, ordered on July 10",
    },
    {
      user_id: 1010,
      customer_name: "William Garcia",
      customer_image: "https://randomuser.me/api/portraits/men/48.jpg",
      isRead: false,
      last_seen: "2025-07-29T09:35:16",
      last_message: "Okay, that's reassuring. Thanks for checking!",
    },
  ],

  // Conversations for chat body
  conversations: [
    {
      user_id: 1001,
      customer_name: "Sarah Johnson",
      customer_image: "https://randomuser.me/api/portraits/women/44.jpg",
      isActive: true,
      last_seen: "2025-07-16T09:35:16",
      conversation: [
        {
          message_id: 1,
          sender: "Sarah Johnson",
          timestamp: "2025-07-16T09:30:16",
          message: "Hi there, I have a question about my order"
        },
        {
          message_id: 2,
          sender: "Agent",
          timestamp: "2025-07-16T09:32:16",
          message: "Hello Sarah, I'd be happy to help. What's your order number?"
        },
        {
          message_id: 3,
          sender: "Sarah Johnson",
          timestamp: "2025-07-16T09:35:16",
          message: "It's #ORD-45678. The delivery date seems to have changed"
        }
      ]
    },
    {
      user_id: 1002,
      customer_name: "Michael Carter",
      customer_image: "https://randomuser.me/api/portraits/men/65.jpg",
      isActive: true,
      last_seen: "2025-07-22T09:35:16",
      conversation: [
        {
          message_id: 1,
          sender: "Agent",
          timestamp: "2025-07-22T09:30:16",
          message: "Good morning Michael, how can I assist you today?"
        },
        {
          message_id: 2,
          sender: "Michael Carter",
          timestamp: "2025-07-22T09:33:16",
          message: "Hi, I need to return an item from my recent purchase"
        },
        {
          message_id: 3,
          sender: "Agent",
          timestamp: "2025-07-22T09:35:16",
          message: "I can help with that. Could you share the item details?"
        }
      ]
    },
    {
      user_id: 1003,
      customer_name: "Emily Davis",
      customer_image: "https://randomuser.me/api/portraits/women/56.jpg",
      isActive: true,
      last_seen: "2025-07-31T09:35:16",
      conversation: [
        {
          message_id: 1,
          sender: "Emily Davis",
          timestamp: "2025-07-31T09:30:16",
          message: "Hello, is this product available in blue?"
        },
        {
          message_id: 2,
          sender: "Agent",
          timestamp: "2025-07-31T09:33:16",
          message: "Let me check our inventory for you Emily"
        },
        {
          message_id: 3,
          sender: "Emily Davis",
          timestamp: "2025-07-31T09:35:16",
          message: "Thanks, I'd like to order it if available"
        }
      ]
    },
    {
      user_id: 1004,
      customer_name: "Daniel Lee",
      customer_image: "https://randomuser.me/api/portraits/men/12.jpg",
      isActive: true,
      last_seen: "2025-07-29T09:35:16",
      conversation: [
        {
          message_id: 1,
          sender: "Daniel Lee",
          timestamp: "2025-07-29T09:30:16",
          message: "I haven't received my shipping confirmation yet"
        },
        {
          message_id: 2,
          sender: "Agent",
          timestamp: "2025-07-29T09:33:16",
          message: "Let me check the status for you Daniel"
        },
        {
          message_id: 3,
          sender: "Daniel Lee",
          timestamp: "2025-07-29T09:35:16",
          message: "Appreciate it, order #ORD-98765"
        }
      ]
    },
    {
      user_id: 1005,
      customer_name: "Sophia Martinez",
      customer_image: "https://randomuser.me/api/portraits/women/30.jpg",
      isActive: false,
      last_seen: "2025-08-08T10:30:11.578",
      conversation: [
        {
          message_id: 1,
          sender: "Sophia Martinez",
          timestamp: "2025-07-30T09:30:16",
          message: "Can I change the shipping address for my order?"
        },
        {
          message_id: 2,
          sender: "Agent",
          timestamp: "2025-07-30T09:33:16",
          message: "We can try if it hasn't shipped yet. What's your order number?"
        },
        {
          message_id: 3,
          sender: "Sophia Martinez",
          timestamp: "2025-07-30T09:35:16",
          message: "It's #ORD-12345, thanks for checking"
        }
      ]
    },
    {
      user_id: 1006,
      customer_name: "Liam Wilson",
      customer_image: "https://randomuser.me/api/portraits/men/23.jpg",
      isActive: false,
      last_seen: "2025-07-28T09:35:16",
      conversation: [
        {
          message_id: 1,
          sender: "Liam Wilson",
          timestamp: "2025-07-28T09:30:16",
          message: "Do you price match with other retailers?"
        },
        {
          message_id: 2,
          sender: "Agent",
          timestamp: "2025-07-28T09:33:16",
          message: "We do in some cases. Can you share the product and competitor price?"
        },
        {
          message_id: 3,
          sender: "Liam Wilson",
          timestamp: "2025-07-28T09:35:16",
          message: "It's your Model X200, priced at $299 elsewhere"
        }
      ]
    },
    {
      user_id: 1007,
      customer_name: "Olivia Brown",
      customer_image: "https://randomuser.me/api/portraits/women/77.jpg",
      isActive: false,
      last_seen: "2025-07-14T09:35:16",
      conversation: [
        {
          message_id: 1,
          sender: "Olivia Brown",
          timestamp: "2025-07-14T09:30:16",
          message: "The item I received is damaged"
        },
        {
          message_id: 2,
          sender: "Agent",
          timestamp: "2025-07-14T09:33:16",
          message: "I'm sorry to hear that. We'll replace it immediately"
        },
        {
          message_id: 3,
          sender: "Olivia Brown",
          timestamp: "2025-07-14T09:35:16",
          message: "Thank you, I've attached photos of the damage"
        }
      ]
    },
    {
      user_id: 1008,
      customer_name: "Noah Anderson",
      customer_image: "https://randomuser.me/api/portraits/men/35.jpg",
      isActive: false,
      last_seen: "2025-07-30T09:35:16",
      conversation: [
        {
          message_id: 1,
          sender: "Noah Anderson",
          timestamp: "2025-07-30T09:30:16",
          message: "When will this be back in stock?"
        },
        {
          message_id: 2,
          sender: "Agent",
          timestamp: "2025-07-30T09:33:16",
          message: "Our system shows it should restock next week"
        },
        {
          message_id: 3,
          sender: "Noah Anderson",
          timestamp: "2025-07-30T09:35:16",
          message: "Great, can you notify me when available?"
        }
      ]
    },
    {
      user_id: 1009,
      customer_name: "Ava Thomas",
      customer_image: "https://randomuser.me/api/portraits/women/88.jpg",
      isActive: false,
      last_seen: "2025-07-15T09:35:16",
      conversation: [
        {
          message_id: 1,
          sender: "Ava Thomas",
          timestamp: "2025-07-15T09:30:16",
          message: "I need help tracking my package"
        },
        {
          message_id: 2,
          sender: "Agent",
          timestamp: "2025-07-15T09:33:16",
          message: "Of course, what's your tracking number?"
        },
        {
          message_id: 3,
          sender: "Ava Thomas",
          timestamp: "2025-07-15T09:35:16",
          message: "It's #TRK-789456, ordered on July 10"
        }
      ]
    },
    {
      user_id: 1010,
      customer_name: "William Garcia",
      customer_image: "https://randomuser.me/api/portraits/men/48.jpg",
      isActive: false,
      last_seen: "2025-07-29T09:35:16",
      conversation: [
        {
          message_id: 1,
          sender: "William Garcia",
          timestamp: "2025-07-29T09:30:16",
          message: "I think I was charged twice for my order"
        },
        {
          message_id: 2,
          sender: "Agent",
          timestamp: "2025-07-29T09:33:16",
          message: "Let me investigate that for you William. What's your order number?"
        },
        {
          message_id: 3,
          sender: "William Garcia",
          timestamp: "2025-07-29T09:35:16",
          message: "It's #ORD-65432, the charge was on July 28"
        },
        {
          message_id: 4,
          sender: "Agent",
          timestamp: "2025-07-29T09:38:16",
          message: "I see one charge that's pending and will drop off. Only one will process"
        },
        {
          message_id: 5,
          sender: "William Garcia",
          timestamp: "2025-07-29T09:40:16",
          message: "Okay, that's reassuring. Thanks for checking!"
        }
      ]
    }
  ]
,
  // chatConversations: [
  //   {
  //     id: 1,
  //     contactId: 10,
  //     contact: "Patrick Johnson",
  //     messages: [
  //       {
  //         id: 1,
  //         senderId: 10,
  //         message:
  //           "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam pharetra felis et tortor scelerisque, id placerat augue hendrerit",
  //         timestamp: "2025-08-21T15:30:00Z",
  //         type: "text",
  //         status: "read",
  //         createdAt: "2025-08-21T15:30:00Z",
  //         updatedAt: "2025-08-21T15:30:00Z",
  //       },
  //       {
  //         id: 2,
  //         senderId: 6,
  //         message:
  //           "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam pharetra felis et tortor scelerisque, id placerat augue hendrerit 👋",
  //         timestamp: "2025-08-21T15:35:00Z",
  //         type: "text",
  //         status: "read",
  //         createdAt: "2025-08-21T15:35:00Z",
  //         updatedAt: "2025-08-21T15:35:00Z",
  //       },
  //       {
  //         id: 3,
  //         senderId: 10,
  //         message: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  //         timestamp: "2025-08-21T15:40:00Z",
  //         type: "text",
  //         status: "read",
  //         createdAt: "2025-08-21T15:40:00Z",
  //         updatedAt: "2025-08-21T15:40:00Z",
  //       },
  //       {
  //         id: 4,
  //         senderId: 10,
  //         message: "Okey 👍",
  //         timestamp: "2025-08-22T10:25:00Z",
  //         type: "text",
  //         status: "read",
  //         createdAt: "2025-08-22T10:25:00Z",
  //         updatedAt: "2025-08-22T10:25:00Z",
  //       },
  //       {
  //         id: 5,
  //         senderId: 10,
  //         message:
  //           "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam pharetra felis et tortor scelerisque, id placerat augue hendrerit",
  //         timestamp: "2025-08-22T10:26:00Z",
  //         type: "text",
  //         status: "read",
  //         createdAt: "2025-08-22T10:26:00Z",
  //         updatedAt: "2025-08-22T10:26:00Z",
  //       },
  //       {
  //         id: 6,
  //         senderId: 6,
  //         message: "Lorem ipsum dolor sit amet 👋",
  //         timestamp: "2025-08-22T10:30:00Z",
  //         type: "text",
  //         status: "sent",
  //         createdAt: "2025-08-22T10:30:00Z",
  //         updatedAt: "2025-08-22T10:30:00Z",
  //       },
  //     ],
  //     lastActivity: "2025-08-22T10:30:00Z",
  //     unreadCount: 0,
  //     createdAt: "2025-08-21T00:00:00Z",
  //     updatedAt: "2025-08-22T10:30:00Z",
  //   },
  //   {
  //     id: 2,
  //     contactId: 11,
  //     contact: "Lisa Williams",
  //     messages: [
  //       {
  //         id: 7,
  //         senderId: 11,
  //         message: "Lorem ipsum dolor sit amet",
  //         timestamp: "2025-08-20T14:00:00Z",
  //         type: "text",
  //         status: "read",
  //         createdAt: "2025-08-20T14:00:00Z",
  //         updatedAt: "2025-08-20T14:00:00Z",
  //       },
  //       {
  //         id: 8,
  //         senderId: 6,
  //         message: "Thank you for the information",
  //         timestamp: "2025-08-20T14:05:00Z",
  //         type: "text",
  //         status: "read",
  //         createdAt: "2025-08-20T14:05:00Z",
  //         updatedAt: "2025-08-20T14:05:00Z",
  //       },
  //     ],
  //     lastActivity: "2025-08-20T14:05:00Z",
  //     unreadCount: 0,
  //     createdAt: "2025-08-20T00:00:00Z",
  //     updatedAt: "2025-08-20T14:05:00Z",
  //   },
  //   {
  //     id: 3,
  //     contactId: 12,
  //     contact: "Josh Adams",
  //     messages: [
  //       {
  //         id: 9,
  //         senderId: 12,
  //         message: "Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
  //         timestamp: "2025-08-20T16:30:00Z",
  //         type: "text",
  //         status: "read",
  //         createdAt: "2025-08-20T16:30:00Z",
  //         updatedAt: "2025-08-20T16:30:00Z",
  //       },
  //       {
  //         id: 10,
  //         senderId: 6,
  //         message: "I'll review this and get back to you",
  //         timestamp: "2025-08-20T16:35:00Z",
  //         type: "text",
  //         status: "read",
  //         createdAt: "2025-08-20T16:35:00Z",
  //         updatedAt: "2025-08-20T16:35:00Z",
  //       },
  //       {
  //         id: 11,
  //         senderId: 12,
  //         message: "Perfect, looking forward to it",
  //         timestamp: "2025-08-20T16:40:00Z",
  //         type: "text",
  //         status: "read",
  //         createdAt: "2025-08-20T16:40:00Z",
  //         updatedAt: "2025-08-20T16:40:00Z",
  //       },
  //       {
  //         id: 12,
  //         senderId: 12,
  //         message: "Any updates on the project?",
  //         timestamp: "2025-08-22T09:15:00Z",
  //         type: "text",
  //         status: "delivered",
  //         createdAt: "2025-08-22T09:15:00Z",
  //         updatedAt: "2025-08-22T09:15:00Z",
  //       },
  //     ],
  //     lastActivity: "2025-08-22T09:15:00Z",
  //     unreadCount: 4,
  //     createdAt: "2025-08-20T00:00:00Z",
  //     updatedAt: "2025-08-22T09:15:00Z",
  //   },
  //   {
  //     id: 4,
  //     contactId: 13,
  //     contact: "Jacob Trevor",
  //     messages: [
  //       {
  //         id: 13,
  //         senderId: 13,
  //         message: "Lorem ipsum dolor sit amet",
  //         timestamp: "2025-08-20T11:20:00Z",
  //         type: "text",
  //         status: "read",
  //         createdAt: "2025-08-20T11:20:00Z",
  //         updatedAt: "2025-08-20T11:20:00Z",
  //       },
  //       {
  //         id: 14,
  //         senderId: 6,
  //         message: "Got it, will process accordingly",
  //         timestamp: "2025-08-20T11:25:00Z",
  //         type: "text",
  //         status: "read",
  //         createdAt: "2025-08-20T11:25:00Z",
  //         updatedAt: "2025-08-20T11:25:00Z",
  //       },
  //       {
  //         id: 15,
  //         senderId: 13,
  //         message: "Great, thanks!",
  //         timestamp: "2025-08-20T11:30:00Z",
  //         type: "text",
  //         status: "read",
  //         createdAt: "2025-08-20T11:30:00Z",
  //         updatedAt: "2025-08-20T11:30:00Z",
  //       },
  //       {
  //         id: 16,
  //         senderId: 13,
  //         message: "Can we discuss the timeline?",
  //         timestamp: "2025-08-22T08:45:00Z",
  //         type: "text",
  //         status: "delivered",
  //         createdAt: "2025-08-22T08:45:00Z",
  //         updatedAt: "2025-08-22T08:45:00Z",
  //       },
  //       {
  //         id: 17,
  //         senderId: 13,
  //         message: "I need to know the exact dates",
  //         timestamp: "2025-08-22T08:50:00Z",
  //         type: "text",
  //         status: "delivered",
  //         createdAt: "2025-08-22T08:50:00Z",
  //         updatedAt: "2025-08-22T08:50:00Z",
  //       },
  //     ],
  //     lastActivity: "2025-08-22T08:50:00Z",
  //     unreadCount: 3,
  //     createdAt: "2025-08-20T00:00:00Z",
  //     updatedAt: "2025-08-22T08:50:00Z",
  //   },
  // ],

  // ===== Additional Users for Messages =====
  additionalUsers: [
    {
      id: 7,
      name: "Jane Cooper",
      email: "jane.cooper@example.com",
      company: "Cooper Energy",
      role: "subscriber",
      avatar: "JC",
      status: "active",
    },
    {
      id: 8,
      name: "Wade Warren",
      email: "wade.warren@example.com",
      company: "Warren Transport",
      role: "subscriber",
      avatar: "WW",
      status: "active",
    },
    {
      id: 9,
      name: "Robert Fox",
      email: "robert.fox@example.com",
      company: "Fox Logistics",
      role: "subscriber",
      avatar: "RF",
      status: "active",
    },
    {
      id: 10,
      name: "Patrick Johnson",
      email: "patrick.johnson@example.com",
      company: "Johnson Energy",
      role: "subscriber",
      avatar: "PJ",
      status: "active",
    },
    {
      id: 11,
      name: "Lisa Williams",
      email: "lisa.williams@example.com",
      company: "Williams Power",
      role: "subscriber",
      avatar: "LW",
      status: "active",
    },
    {
      id: 12,
      name: "Josh Adams",
      email: "josh.adams@example.com",
      company: "Adams Energy",
      role: "subscriber",
      avatar: "JA",
      status: "active",
    },
    {
      id: 13,
      name: "Jacob Trevor",
      email: "jacob.trevor@example.com",
      company: "Trevor Transport",
      role: "subscriber",
      avatar: "JT",
      status: "active",
    },
    {
      id: 14,
      name: "Danny Johnson",
      email: "danny.johnson@example.com",
      company: "Johnson Logistics",
      role: "subscriber",
      avatar: "DJ",
      status: "active",
    },
    {
      id: 15,
      name: "Patricia Heather",
      email: "patricia.heather@example.com",
      company: "Heather Energy",
      role: "subscriber",
      avatar: "PH",
      status: "active",
    },
    {
      id: 16,
      name: "Michael Thomas",
      email: "michael.thomas@example.com",
      company: "Thomas Power",
      role: "subscriber",
      avatar: "MT",
      status: "active",
    },
    {
      id: 17,
      name: "Linda Robert",
      email: "linda.robert@example.com",
      company: "Robert Energy",
      role: "subscriber",
      avatar: "LR",
      status: "active",
    },
  ],

  // ===== Settings Data =====
  settings: {
    // ===== Admin Information =====
    adminInformation: {
      id: 1,
      companyName: "PLX Energy Transportation Expertise",
      accountType: "Admin",
      emailAddress: "plx123@gmail.com",
      phoneNumber: "(704) 555-0127",
      address: "123 Energy Drive, Houston, TX 77001",
      website: "https://plxenergy.com",
      industry: "Energy Transportation & Logistics",
      foundedYear: 2015,
      employeeCount: "50-100",
      timezone: "UTC + 7",
      dateFormat: "MM/DD/YYYY",
      currency: "USD",
      language: "English",
    },

    // ===== User Preferences =====
    userPreferences: [
      {
        userId: 6, // Miguel Trevino
        timezone: "UTC + 7",
        dateFormat: "MM/DD/YYYY",
        timeFormat: "12-hour",
        currency: "USD",
        language: "English",
        theme: "light",
        sidebarCollapsed: false,
        notifications: {
          email: true,
          sms: false,
          push: true,
          inApp: true,
        },
        security: {
          sessionTimeout: 30,
          passwordExpiry: 500,
          twoFactorEnabled: false,
          loginNotifications: true,
          suspiciousActivityAlerts: true,
        },
      },
      {
        userId: 5, // Jenny Wilson
        timezone: "UTC + 8",
        dateFormat: "DD/MM/YYYY",
        timeFormat: "24-hour",
        currency: "USD",
        language: "English",
        theme: "dark",
        sidebarCollapsed: true,
        notifications: {
          email: true,
          sms: true,
          push: false,
          inApp: true,
        },
        security: {
          sessionTimeout: 60,
          passwordExpiry: 365,
          twoFactorEnabled: true,
          loginNotifications: true,
          suspiciousActivityAlerts: false,
        },
      },
    ],

    // ===== Notification Settings =====
    notificationSettings: {
      globalDefaults: {
        emailNotifications: true,
        smsNotifications: false,
        pushNotifications: true,
        inAppNotifications: true,
      },
      notificationTypes: [
        {
          id: 1,
          name: "New Nomination",
          description: "When a new nomination is submitted",
          email: true,
          sms: false,
          push: true,
          inApp: true,
        },
        {
          id: 2,
          name: "Meeting Reminders",
          description: "Meeting reminders and updates",
          email: true,
          sms: true,
          push: true,
          inApp: true,
        },
        {
          id: 3,
          name: "Schedule Updates",
          description: "Changes to transportation schedules",
          email: true,
          sms: false,
          push: true,
          inApp: true,
        },
        {
          id: 4,
          name: "Security Alerts",
          description: "Login attempts and security notifications",
          email: true,
          sms: true,
          push: false,
          inApp: true,
        },
        {
          id: 5,
          name: "System Updates",
          description: "Platform maintenance and updates",
          email: true,
          sms: false,
          push: false,
          inApp: true,
        },
      ],
    },

    // ===== Security Settings =====
    securitySettings: {
      globalDefaults: {
        sessionTimeout: 30,
        passwordExpiry: 500,
        twoFactorEnabled: false,
        passwordComplexity: "strong",
        maxLoginAttempts: 5,
        lockoutDuration: 15,
        requirePasswordChange: true,
      },
      passwordPolicies: {
        minLength: 8,
        requireUppercase: true,
        requireLowercase: true,
        requireNumbers: true,
        requireSpecialChars: true,
        preventCommonPasswords: true,
        preventUsernameInPassword: true,
      },
      sessionPolicies: {
        maxConcurrentSessions: 3,
        idleTimeout: 30,
        rememberDevice: true,
        forceLogoutOnPasswordChange: true,
      },
      twoFactorSettings: {
        methods: ["email", "sms", "authenticator"],
        backupCodes: true,
        rememberDevice: true,
        requireOnAdmin: true,
        requireOnSensitiveOperations: true,
      },
    },

    // ===== Integrations =====
    integrations: [
      {
        id: 1,
        name: "Calendly",
        description: "Track with real-time appointment bookings and reminders.",
        status: "connected",
        apiKey: "cal_1234567890abcdef",
        webhookUrl: "https://plxenergy.com/webhooks/calendly",
        settings: {
          autoSync: true,
          syncInterval: "5min",
          notifications: true,
          calendarIntegration: true,
        },
        lastSync: "2025-08-22T10:30:00Z",
        syncStatus: "success",
        errorCount: 0,
        createdAt: "2025-01-15T00:00:00Z",
        updatedAt: "2025-08-22T10:30:00Z",
      },
      {
        id: 2,
        name: "DataPark",
        description:
          "Easily upload, store, and manage your essential recovery documents in a secure, organized space.",
        status: "connected",
        apiKey: "dp_9876543210fedcba",
        webhookUrl: "https://plxenergy.com/webhooks/datapark",
        settings: {
          autoSync: true,
          syncInterval: "10min",
          notifications: true,
          documentManagement: true,
          backupEnabled: true,
        },
        lastSync: "2025-08-22T10:25:00Z",
        syncStatus: "success",
        errorCount: 0,
        createdAt: "2025-03-20T00:00:00Z",
        updatedAt: "2025-08-22T10:25:00Z",
      },
      {
        id: 3,
        name: "Stripe",
        description:
          "Process payments and manage billing for transportation services.",
        status: "disconnected",
        apiKey: "",
        webhookUrl: "",
        settings: {
          autoSync: false,
          syncInterval: "disabled",
          notifications: false,
          paymentProcessing: false,
        },
        lastSync: null,
        syncStatus: "disabled",
        errorCount: 0,
        createdAt: "2025-06-10T00:00:00Z",
        updatedAt: "2025-06-10T00:00:00Z",
      },
      {
        id: 4,
        name: "Google Maps",
        description:
          "Real-time route optimization and location tracking for transportation.",
        status: "connected",
        apiKey: "gmaps_abcdef1234567890",
        webhookUrl: "",
        settings: {
          autoSync: true,
          syncInterval: "1min",
          notifications: false,
          routeOptimization: true,
          trafficUpdates: true,
        },
        lastSync: "2025-08-22T10:28:00Z",
        syncStatus: "success",
        errorCount: 0,
        createdAt: "2025-02-15T00:00:00Z",
        updatedAt: "2025-08-22T10:28:00Z",
      },
    ],

    // ===== System Configuration =====
    systemConfig: {
      platform: {
        name: "PLX Energy Transportation Platform",
        version: "2.1.0",
        environment: "production",
        maintenanceMode: false,
        lastMaintenance: "2025-08-15T02:00:00Z",
      },
      database: {
        type: "PostgreSQL",
        version: "15.0",
        backupFrequency: "daily",
        lastBackup: "2025-08-22T02:00:00Z",
        retentionPeriod: "30 days",
      },
      email: {
        provider: "SendGrid",
        dailyLimit: 10000,
        usedToday: 1250,
        templates: [
          "welcome",
          "reset-password",
          "meeting-reminder",
          "nomination-update",
        ],
      },
      storage: {
        totalSpace: "500GB",
        usedSpace: "125GB",
        availableSpace: "375GB",
        fileTypes: ["pdf", "xlsx", "docx", "jpg", "png"],
      },
    },
  },

  // ===== Dashboard: Notifications dropdown =====
  notifications: [
    {
      id: 1,
      type: "nomination",
      icon: "person",
      iconColor: "blue",
      title: "New nomination request from Sarah Johnson requires your action",
      message: "New nomination request from Sarah Johnson requires your action",
      timestamp: "12:58 PM",
      timeAgo: "Just now",
      priority: "high",
      status: "unread",
      actions: [
        {
          id: 1,
          label: "Review",
          type: "secondary",
          icon: "eye",
          action: "review_nomination",
          nominationId: "3583482",
        },
        {
          id: 2,
          label: "Confirm",
          type: "primary",
          icon: "check",
          action: "confirm_nomination",
          nominationId: "3583482",
        },
      ],
      userId: 1,
      nominationId: "3583482",
      isActionable: true,
      createdAt: "2025-08-22T12:58:00Z",
      updatedAt: "2025-08-22T12:58:00Z",
    },
    {
      id: 2,
      type: "schedule",
      icon: "check-circle",
      iconColor: "blue",
      title: "Schedule has been updated successfully.",
      message: "Schedule has been updated successfully.",
      timestamp: "2 hours ago",
      timeAgo: "2 hours ago",
      priority: "medium",
      status: "read",
      actions: [],
      userId: 6,
      scheduleId: 1,
      isActionable: false,
      createdAt: "2025-08-22T10:30:00Z",
      updatedAt: "2025-08-22T10:30:00Z",
    },
    {
      id: 3,
      type: "meeting",
      icon: "calendar",
      iconColor: "blue",
      title:
        "Tom has requested a meeting at 5:00 PM on 12/02/2025 via Calendly.",
      message:
        "Tom has requested a meeting at 5:00 PM on 12/02/2025 via Calendly.",
      timestamp: "8 hours ago",
      timeAgo: "8 hours ago",
      priority: "medium",
      status: "read",
      actions: [],
      userId: 6,
      meetingId: 9,
      isActionable: false,
      createdAt: "2025-08-22T04:00:00Z",
      updatedAt: "2025-08-22T04:00:00Z",
    },
    {
      id: 4,
      type: "security",
      icon: "shield",
      iconColor: "red",
      title: "New login detected from unknown device",
      message: "New login detected from unknown device in Houston, TX",
      timestamp: "1 day ago",
      timeAgo: "1 day ago",
      priority: "high",
      status: "unread",
      actions: [
        {
          id: 3,
          label: "Review",
          type: "secondary",
          icon: "eye",
          action: "review_login",
          loginId: "login_123",
        },
        {
          id: 4,
          label: "Block Device",
          type: "danger",
          icon: "block",
          action: "block_device",
          deviceId: "device_456",
        },
      ],
      userId: 6,
      loginId: "login_123",
      isActionable: true,
      createdAt: "2025-08-21T15:30:00Z",
      updatedAt: "2025-08-21T15:30:00Z",
    },
    {
      id: 5,
      type: "payment",
      icon: "credit-card",
      iconColor: "green",
      title: "Payment received for nomination #3583475",
      message: "Payment of $2,500 received for nomination #3583475",
      timestamp: "2 days ago",
      timeAgo: "2 days ago",
      priority: "low",
      status: "read",
      actions: [
        {
          id: 5,
          label: "View Receipt",
          type: "secondary",
          icon: "file",
          action: "view_receipt",
          paymentId: "pay_789",
        },
      ],
      userId: 6,
      paymentId: "pay_789",
      nominationId: "3583475",
      isActionable: true,
      createdAt: "2025-08-20T14:20:00Z",
      updatedAt: "2025-08-20T14:20:00Z",
    },
    {
      id: 6,
      type: "system",
      icon: "settings",
      iconColor: "gray",
      title: "System maintenance scheduled for tonight",
      message: "System maintenance scheduled for tonight at 2:00 AM EST",
      timestamp: "3 days ago",
      timeAgo: "3 days ago",
      priority: "medium",
      status: "read",
      actions: [],
      userId: null,
      maintenanceId: "maint_001",
      isActionable: false,
      createdAt: "2025-08-19T10:00:00Z",
      updatedAt: "2025-08-19T10:00:00Z",
    },
  ],

  // ===== Notification Types & Templates =====
  notificationTypes: [
    {
      id: 1,
      name: "nomination",
      displayName: "Nomination",
      icon: "person",
      iconColor: "blue",
      description: "Notifications related to nomination requests and updates",
      defaultPriority: "high",
      defaultActions: ["Review", "Confirm"],
      isActionable: true,
      canDismiss: true,
      expiresAfter: "7 days",
    },
    {
      id: 2,
      name: "schedule",
      displayName: "Schedule",
      icon: "check-circle",
      iconColor: "blue",
      description: "Notifications about schedule changes and updates",
      defaultPriority: "medium",
      defaultActions: [],
      isActionable: false,
      canDismiss: true,
      expiresAfter: "3 days",
    },
    {
      id: 3,
      name: "meeting",
      displayName: "Meeting",
      icon: "calendar",
      iconColor: "blue",
      description: "Meeting requests and reminders",
      defaultPriority: "medium",
      defaultActions: ["Accept", "Decline"],
      isActionable: true,
      canDismiss: true,
      expiresAfter: "24 hours",
    },
    {
      id: 4,
      name: "security",
      displayName: "Security",
      icon: "shield",
      iconColor: "red",
      description: "Security alerts and login notifications",
      defaultPriority: "high",
      defaultActions: ["Review", "Block"],
      isActionable: true,
      canDismiss: false,
      expiresAfter: "30 days",
    },
    {
      id: 5,
      name: "payment",
      displayName: "Payment",
      icon: "credit-card",
      iconColor: "green",
      description: "Payment confirmations and receipts",
      defaultPriority: "low",
      defaultActions: ["View Receipt"],
      isActionable: true,
      canDismiss: true,
      expiresAfter: "90 days",
    },
    {
      id: 6,
      name: "system",
      displayName: "System",
      icon: "settings",
      iconColor: "gray",
      description: "System updates and maintenance notifications",
      defaultPriority: "medium",
      defaultActions: [],
      isActionable: false,
      canDismiss: true,
      expiresAfter: "7 days",
    },
  ],

  // ===== Notification Actions =====
  notificationActions: [
    {
      id: 1,
      name: "review",
      label: "Review",
      type: "secondary",
      icon: "eye",
      action: "review_item",
      description: "Review the notification details",
    },
    {
      id: 2,
      name: "confirm",
      label: "Confirm",
      type: "primary",
      icon: "check",
      action: "confirm_item",
      description: "Confirm the action",
    },
    {
      id: 3,
      name: "accept",
      label: "Accept",
      type: "primary",
      icon: "check",
      action: "accept_item",
      description: "Accept the request",
    },
    {
      id: 4,
      name: "decline",
      label: "Decline",
      type: "danger",
      icon: "x",
      action: "decline_item",
      description: "Decline the request",
    },
    {
      id: 5,
      name: "block",
      label: "Block",
      type: "danger",
      icon: "block",
      action: "block_item",
      description: "Block the item",
    },
    {
      id: 6,
      name: "view_receipt",
      label: "View Receipt",
      type: "secondary",
      icon: "file",
      action: "view_receipt",
      description: "View payment receipt",
    },
  ],

  // ===== Notification Statistics =====
  notificationStats: {
    total: 156,
    unread: 23,
    today: 8,
    thisWeek: 34,
    thisMonth: 156,
    byType: {
      nomination: 45,
      schedule: 38,
      meeting: 32,
      security: 18,
      payment: 15,
      system: 8,
    },
    byPriority: {
      high: 28,
      medium: 89,
      low: 39,
    },
  },

  // ===== Schedule Data =====
  schedules: [
    {
      id: 1,
      assignedUser: "Sarah Chen",
      companyName: "Chen Logistics",
      assetGrouup:'Upstream',
      commodityType:"Natural Gas",
      transportationMode:"Pipeline",
      assignedUserId: 1,
      email: "debra.holt@example.com",
      fileName: "Schedule_Jan.xlsx",
      fileNameCode: "SCHEDULE_JAN_XLSX",
      fileSize: "2.4 MB",
      fileSizeBytes: 2516582,
      fileType: "xlsx",
      fileTypeCode: "XLSX",
      dateUploaded: "2025-08-21",
      timeUploaded: "3:00PM",
      uploadedAt: "2025-08-21T15:00:00Z",
      status: "active",
      statusCode: "ACTIVE",
      statusColor: "green",
      scheduleType: "monthly",
      scheduleTypeCode: "MONTHLY",
      month: "January",
      monthCode: "JANUARY",
      year: 2025,
      isActive: true,
      isPublic: false,
      downloadCount: 0,
      lastDownloaded: null,
      createdAt: "2025-08-21T15:00:00Z",
      updatedAt: "2025-08-21T15:00:00Z",
    },
    {
      id: 2,
      assignedUser: "Esther Howard",
      companyName: "Howard Transport",
      assetGrouup:'Midstream',
      commodityType:"Electricity",
      transportationMode:"Trucking",
      assignedUserId: 2,
      email: "willie.jennings@example.com",
      fileName: "Schedule_Jan.xlsx",
      fileNameCode: "SCHEDULE_JAN_XLSX",
      fileSize: "2.1 MB",
      fileSizeBytes: 2202009,
      fileType: "xlsx",
      fileTypeCode: "XLSX",
      dateUploaded: "2025-08-21",
      timeUploaded: "3:00PM",
      uploadedAt: "2025-08-21T15:00:00Z",
      status: "active",
      statusCode: "ACTIVE",
      statusColor: "green",
      scheduleType: "monthly",
      scheduleTypeCode: "MONTHLY",
      month: "January",
      monthCode: "JANUARY",
      year: 2025,
      isActive: true,
      isPublic: false,
      downloadCount: 0,
      lastDownloaded: null,
      createdAt: "2025-08-21T15:00:00Z",
      updatedAt: "2025-08-21T15:00:00Z",
    },
    {
      id: 3,
      assignedUser: "Brooklyn Simmons",
      companyName: "Simmons Freight",
      commodityType:"Natural Gas",
      transportationMode:"Railcar",
      assetGrouup:'Downstream',
      assignedUserId: 3,
      email: "michelle.rivera@example.com",
      fileName: "Schedule_Jan.xlsx",
      fileNameCode: "SCHEDULE_JAN_XLSX",
      fileSize: "2.8 MB",
      fileSizeBytes: 2936012,
      fileType: "xlsx",
      fileTypeCode: "XLSX",
      dateUploaded: "2025-08-21",
      timeUploaded: "3:00PM",
      uploadedAt: "2025-08-21T15:00:00Z",
      status: "active",
      statusCode: "ACTIVE",
      statusColor: "green",
      scheduleType: "monthly",
      scheduleTypeCode: "MONTHLY",
      month: "January",
      monthCode: "JANUARY",
      year: 2025,
      isActive: true,
      isPublic: false,
      downloadCount: 0,
      lastDownloaded: null,
      createdAt: "2025-08-21T15:00:00Z",
      updatedAt: "2025-08-21T15:00:00Z",
    },
    {
      id: 4,
      assignedUser: "Leslie Alexander",
      companyName: "Alexander Transport",
      assetGrouup:'Renewable Energy',
      commodityType:"Electricity",
      transportationMode:"Pipeline",
      assignedUserId: 4,
      email: "bill.sanders@example.com",
      fileName: "Schedule_Jan.xlsx",
      fileNameCode: "SCHEDULE_JAN_XLSX",
      fileSize: "2.2 MB",
      fileSizeBytes: 2306867,
      fileType: "xlsx",
      fileTypeCode: "XLSX",
      dateUploaded: "2025-08-21",
      timeUploaded: "3:00PM",
      uploadedAt: "2025-08-21T15:00:00Z",
      status: "active",
      statusCode: "ACTIVE",
      statusColor: "green",
      scheduleType: "monthly",
      scheduleTypeCode: "MONTHLY",
      month: "January",
      monthCode: "JANUARY",
      year: 2025,
      isActive: true,
      isPublic: false,
      downloadCount: 0,
      lastDownloaded: null,
      createdAt: "2025-08-21T15:00:00Z",
      updatedAt: "2025-08-21T15:00:00Z",
    },
    {
      id: 5,
      assignedUser: "Jenny Wilson",
      companyName: "Wilson Logistics",
      assetGrouup:'Energy Infrastructure',
      commodityType:"Natural Gas",
      transportationMode:"Pipeline",
      assignedUserId: 5,
      email: "deanna.curtis@example.com",
      fileName: "Schedule_Jan.xlsx",
      fileNameCode: "SCHEDULE_JAN_XLSX",
      fileSize: "2.6 MB",
      fileSizeBytes: 2726297,
      fileType: "xlsx",
      fileTypeCode: "XLSX",
      dateUploaded: "2025-08-21",
      timeUploaded: "3:00PM",
      uploadedAt: "2025-08-21T15:00:00Z",
      status: "active",
      statusCode: "ACTIVE",
      statusColor: "green",
      scheduleType: "monthly",
      scheduleTypeCode: "MONTHLY",
      month: "January",
      monthCode: "JANUARY",
      year: 2025,
      isActive: true,
      isPublic: false,
      downloadCount: 0,
      lastDownloaded: null,
      createdAt: "2025-08-21T15:00:00Z",
      updatedAt: "2025-08-21T15:00:00Z",
    },
    {
      id: 6,
      assignedUser: "Jenny Wilson",
      companyName: "Wilson Logistics",
      assetGrouup:'Upstream',
      commodityType:"Electricity",
      transportationMode:"Trucking",
      assignedUserId: 5,
      email: "deanna.curtis@example.com",
      fileName: "Schedule_Jan.xlsx",
      fileNameCode: "SCHEDULE_JAN_XLSX",
      fileSize: "2.6 MB",
      fileSizeBytes: 2726297,
      fileType: "xlsx",
      fileTypeCode: "XLSX",
      dateUploaded: "2025-08-21",
      timeUploaded: "3:00PM",
      uploadedAt: "2025-08-21T15:00:00Z",
      status: "active",
      statusCode: "ACTIVE",
      statusColor: "green",
      scheduleType: "monthly",
      scheduleTypeCode: "MONTHLY",
      month: "January",
      monthCode: "JANUARY",
      year: 2025,
      isActive: true,
      isPublic: false,
      downloadCount: 0,
      lastDownloaded: null,
      createdAt: "2025-08-21T15:00:00Z",
      updatedAt: "2025-08-21T15:00:00Z",
    },
  ],

  // ===== Dashboard: Actions/meta shown on this screen =====
  dashboardActions: [
    { key: "createNomination", label: "Create New Nomination" },
    { key: "viewAllNominations", label: "View all" },
    { key: "uploadSchedule", label: "Upload Schedule" },
    { key: "createMeeting", label: "Schedule Meeting" },
    { key: "sendMessage", label: "Send Message" },
  ],

  // ===== Status Types =====
  statusTypes: [
    {
      id: 1,
      name: "Submitted",
      nameCode: "SUBMITTED",
      color: "blue",
      colorCode: "BLUE",
      description: "Nomination has been submitted and is under review",
      status: "active",
      statusCode: "ACTIVE",
      isActive: true,
      createdAt: "2025-01-01T00:00:00Z",
      updatedAt: "2025-08-22T00:00:00Z",
    },
    {
      id: 2,
      name: "Confirmed",
      nameCode: "CONFIRMED",
      color: "green",
      colorCode: "GREEN",
      description: "Nomination has been confirmed and approved",
      status: "active",
      statusCode: "ACTIVE",
      isActive: true,
      createdAt: "2025-01-01T00:00:00Z",
      updatedAt: "2025-08-22T00:00:00Z",
    },
    {
      id: 3,
      name: "Pending",
      nameCode: "PENDING",
      color: "yellow",
      colorCode: "YELLOW",
      description: "Nomination is pending additional information",
      status: "active",
      statusCode: "ACTIVE",
      isActive: true,
      createdAt: "2025-01-01T00:00:00Z",
      updatedAt: "2025-08-22T00:00:00Z",
    },
    {
      id: 4,
      name: "Rejected",
      nameCode: "REJECTED",
      color: "red",
      colorCode: "RED",
      description: "Nomination has been rejected",
      status: "active",
      statusCode: "ACTIVE",
      isActive: true,
      createdAt: "2025-01-01T00:00:00Z",
      updatedAt: "2025-08-22T00:00:00Z",
    },
    {
      id: 5,
      name: "In Progress",
      nameCode: "IN_PROGRESS",
      color: "orange",
      colorCode: "ORANGE",
      description: "Nomination is currently being processed",
      status: "active",
      statusCode: "ACTIVE",
      isActive: true,
      createdAt: "2025-01-01T00:00:00Z",
      updatedAt: "2025-08-22T00:00:00Z",
    },
  ],

  // ===== Priority Levels =====
  priorityLevels: [
    {
      id: 1,
      name: "Low",
      nameCode: "LOW",
      color: "gray",
      colorCode: "GRAY",
      description: "Standard priority",
      status: "active",
      statusCode: "ACTIVE",
      isActive: true,
      createdAt: "2025-01-01T00:00:00Z",
      updatedAt: "2025-08-22T00:00:00Z",
    },
    {
      id: 2,
      name: "Medium",
      nameCode: "MEDIUM",
      color: "yellow",
      colorCode: "YELLOW",
      description: "Medium priority",
      status: "active",
      statusCode: "ACTIVE",
      isActive: true,
      createdAt: "2025-01-01T00:00:00Z",
      updatedAt: "2025-08-22T00:00:00Z",
    },
    {
      id: 3,
      name: "High",
      nameCode: "HIGH",
      color: "orange",
      colorCode: "ORANGE",
      description: "High priority",
      status: "active",
      statusCode: "ACTIVE",
      isActive: true,
      createdAt: "2025-01-01T00:00:00Z",
      updatedAt: "2025-08-22T00:00:00Z",
    },
    {
      id: 4,
      name: "Urgent",
      nameCode: "URGENT",
      color: "red",
      colorCode: "RED",
      description: "Urgent priority",
      status: "active",
      statusCode: "ACTIVE",
      isActive: true,
      createdAt: "2025-01-01T00:00:00Z",
      updatedAt: "2025-08-22T00:00:00Z",
    },
  ],

  // ===== Time Zones =====
  timeZones: [
    {
      id: 1,
      name: "Pacific Time - US",
      nameCode: "PACIFIC_TIME_US",
      abbreviation: "PST/PDT",
      abbreviationCode: "PST_PDT",
      offset: "-8/-7",
      offsetCode: "MINUS_8_MINUS_7",
      status: "active",
      statusCode: "ACTIVE",
      isActive: true,
      isDefault: false,
      createdAt: "2025-01-01T00:00:00Z",
      updatedAt: "2025-08-22T00:00:00Z",
    },
    {
      id: 2,
      name: "Central Time - US",
      nameCode: "CENTRAL_TIME_US",
      abbreviation: "CST/CDT",
      abbreviationCode: "CST_CDT",
      offset: "-6/-5",
      offsetCode: "MINUS_6_MINUS_5",
      status: "active",
      statusCode: "ACTIVE",
      isActive: true,
      isDefault: true,
      createdAt: "2025-01-01T00:00:00Z",
      updatedAt: "2025-08-22T00:00:00Z",
    },
    {
      id: 3,
      name: "Eastern Time - US",
      nameCode: "EASTERN_TIME_US",
      abbreviation: "EST/EDT",
      abbreviationCode: "EST_EDT",
      offset: "-5/-4",
      offsetCode: "MINUS_5_MINUS_4",
      status: "active",
      statusCode: "ACTIVE",
      isActive: true,
      isDefault: false,
      createdAt: "2025-01-01T00:00:00Z",
      updatedAt: "2025-08-22T00:00:00Z",
    },
    {
      id: 4,
      name: "Mountain Time - US",
      nameCode: "MOUNTAIN_TIME_US",
      abbreviation: "MST/MDT",
      abbreviationCode: "MST_MDT",
      offset: "-7/-6",
      offsetCode: "MINUS_7_MINUS_6",
      status: "active",
      statusCode: "ACTIVE",
      isActive: true,
      isDefault: false,
      createdAt: "2025-01-01T00:00:00Z",
      updatedAt: "2025-08-22T00:00:00Z",
    },
    {
      id: 5,
      name: "Alaska Time",
      nameCode: "ALASKA_TIME",
      abbreviation: "AKST/AKDT",
      abbreviationCode: "AKST_AKDT",
      offset: "-9/-8",
      offsetCode: "MINUS_9_MINUS_8",
      status: "active",
      statusCode: "ACTIVE",
      isActive: true,
      isDefault: false,
      createdAt: "2025-01-01T00:00:00Z",
      updatedAt: "2025-08-22T00:00:00Z",
    },
  ],
};
