 
import type { Metadata } from "next";
import { Roboto, Manrope } from "next/font/google";
import  { Toaster } from 'react-hot-toast';
import "./globals.css";

const roboto = Roboto({
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  subsets: ["latin"],
  variable: "--font-roboto",
});

const manrope = Manrope({
  weight: ['200', '300', '400', '500', '600', '700', '800'],
  subsets: ["latin"],
  variable: "--font-manrope",
});

export const metadata: Metadata = {
  title: "miguel",
  description: "Generated by create next app",
  // icons: {
  //   icon: "../logo-fav.svg",
  // },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable} ${manrope.variable} antialiased`}
      >
        {children}     
        <Toaster/>   
      </body>
    </html>
  );
}
